import { describe, expect, it } from "vitest";
import {
    type Options,
    generateTsconfig,
    generateTsconfigCypress,
    generateTsconfigLib,
    generateTsconfigPageobjects,
    generateTsconfigSelectors,
} from "./write-config";

expect.addSnapshotSerializer({
    test(value) {
        return typeof value === "string";
    },
    serialize(value) {
        return String(value);
    },
});

it("should not reference tsconfig.pageobjects.json when pageobjects are not detected", async () => {
    expect.assertions(1);
    const options: Options = {
        name: "@fkui/vue",
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "vitest",
        enablePageobjects: false,
        enableSelectors: true,
    };
    const result = await generateTsconfig(options);
    expect(result).toMatchInlineSnapshot(`
        /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

        {
            "extends": "@forsakringskassan/vite-lib-config/tsconfig.root.json",
            "references": [
                {
                    "path": "./tsconfig.lib.json"
                },
                {
                    "path": "./tsconfig.cypress.json"
                },
                {
                    "path": "./tsconfig.selectors.json"
                }
            ]
        }

    `);
});

it("should not reference tsconfig.selectors.json when selectors are not detected", async () => {
    expect.assertions(1);
    const options: Options = {
        name: "@fkui/vue",
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "vitest",
        enablePageobjects: true,
        enableSelectors: false,
    };
    const result = await generateTsconfig(options);
    expect(result).toMatchInlineSnapshot(`
        /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

        {
            "extends": "@forsakringskassan/vite-lib-config/tsconfig.root.json",
            "references": [
                {
                    "path": "./tsconfig.lib.json"
                },
                {
                    "path": "./tsconfig.cypress.json"
                },
                {
                    "path": "./tsconfig.pageobjects.json"
                }
            ]
        }

    `);
});

describe("with vitest as test runner", () => {
    const options: Options = {
        name: "@fkui/vue",
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "vitest",
        enablePageobjects: true,
        enableSelectors: true,
    };

    it("should generate tsconfig.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfig(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.root.json",
                "references": [
                    {
                        "path": "./tsconfig.lib.json"
                    },
                    {
                        "path": "./tsconfig.cypress.json"
                    },
                    {
                        "path": "./tsconfig.pageobjects.json"
                    },
                    {
                        "path": "./tsconfig.selectors.json"
                    }
                ]
            }

        `);
    });

    it("should generate tsconfig.lib.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigLib(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
                "compilerOptions": {
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.cypress.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigCypress(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": [
                    "../../cypress/tsconfig.json",
                    "@forsakringskassan/vite-lib-config/tsconfig.cypress.json"
                ],
                "compilerOptions": {
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.selectors.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigSelectors(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.selectors.json"
            }

        `);
    });

    it("should generate tsconfig.pageobjects.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigPageobjects(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.pageobjects.json"
            }

        `);
    });
});

describe("with jest as test runner", () => {
    const options: Options = {
        name: "@fkui/vue",
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "jest",
        enablePageobjects: true,
        enableSelectors: true,
    };

    it("should generate tsconfig.json extending", async () => {
        expect.assertions(1);
        const result = await generateTsconfig(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": [
                    "@forsakringskassan/vite-lib-config/tsconfig.root.json",
                    "@fkui/tsconfig/recommended",
                    "@fkui/tsconfig/vue"
                ],
                "compilerOptions": {
                    "declarationDir": "temp/jest",
                    "paths": {
                        "@fkui/vue": ["./src/index.ts"]
                    }
                },
                "include": ["src/@types/*.ts"],
                "exclude": ["src/@types/cypress.d.ts"],
                "references": [
                    {
                        "path": "./tsconfig.lib.json"
                    },
                    {
                        "path": "./tsconfig.cypress.json"
                    },
                    {
                        "path": "./tsconfig.pageobjects.json"
                    },
                    {
                        "path": "./tsconfig.selectors.json"
                    }
                ]
            }

        `);
    });

    it("should generate tsconfig.lib.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigLib(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
                "compilerOptions": {
                    "types": ["node", "jest", "vite/client"],
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.cypress.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigCypress(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": [
                    "../../cypress/tsconfig.json",
                    "@forsakringskassan/vite-lib-config/tsconfig.cypress.json"
                ],
                "compilerOptions": {
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.selectors.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigSelectors(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.selectors.json"
            }

        `);
    });

    it("should generate tsconfig.pageobjects.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigPageobjects(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.pageobjects.json"
            }

        `);
    });
});
