import fs from "node:fs/promises";
import path from "node:path";

const boilerplate = `/* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */`;

interface PackageJson {
    name: string;
    exports?: Record<string, unknown>;
}

interface TSConfig {
    extends?: string | string[];
    references?: Array<{ path: string }>;
    compilerOptions?: {
        declarationDir?: string;
        types?: string[];
        paths?: Record<string, string[]>;
    };
    include?: string[];
    exclude?: string[];
}

/**
 * @internal
 */
export interface Options {
    /** name from package.json */
    name: string;

    /** path to cypress tsconfig */
    cypressConfigPath: string;

    /** test runner used in this repository */
    testRunner: "jest" | "vitest";

    /* true if selector objects are present */
    enableSelectors: boolean;

    /* true if cypress pageobjects are present */
    enablePageobjects: boolean;
}

function detectTestRunner(flags: Set<string>): "jest" | "vitest" {
    if (flags.has("--with-jest")) {
        return "jest";
    } else if (flags.has("--with-vitest")) {
        return "vitest";
    } else {
        return "vitest";
    }
}

async function serializeJson(data: unknown): Promise<string> {
    const { format, resolveConfig } = await import("prettier");
    const content = JSON.stringify(data, null, 4);
    const filepath = "tsconfig.json";
    const config = await resolveConfig(filepath, { editorconfig: true });
    const formatted = await format(content, { ...config, filepath });
    return formatted;
}

/**
 * @internal
 */
export async function generateTsconfig(options: Options): Promise<string> {
    const { name, enablePageobjects, enableSelectors, testRunner } = options;
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.root.json",
        compilerOptions: undefined,
        include: undefined,
        exclude: undefined,
        references: [
            { path: "./tsconfig.lib.json" },
            { path: "./tsconfig.cypress.json" },
        ],
    };
    if (testRunner === "jest") {
        config.extends = [
            "@forsakringskassan/vite-lib-config/tsconfig.root.json",
            "@fkui/tsconfig/recommended",
            "@fkui/tsconfig/vue",
        ];
        config.compilerOptions = {
            declarationDir: "temp/jest",
            paths: {
                [name]: ["./src/index.ts"],
            },
        };
        config.include = ["src/@types/*.ts"];
        config.exclude = ["src/@types/cypress.d.ts"];
    }
    if (enablePageobjects) {
        config.references?.push({ path: "./tsconfig.pageobjects.json" });
    }
    if (enableSelectors) {
        config.references?.push({ path: "./tsconfig.selectors.json" });
    }
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigLib(options: Options): Promise<string> {
    const { name, testRunner } = options;
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
        compilerOptions: {
            types:
                testRunner === "jest"
                    ? ["node", "jest", "vite/client"]
                    : undefined,
            paths: {
                [`${name}/cypress`]: ["./src/cypress/index.ts"],
                [`${name}/selectors`]: ["./src/selectors/index.ts"],
                [name]: ["./src/index.ts"],
            },
        },
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigCypress(
    options: Options,
): Promise<string> {
    const { name, cypressConfigPath } = options;
    const config: TSConfig = {
        extends: [
            cypressConfigPath,
            "@forsakringskassan/vite-lib-config/tsconfig.cypress.json",
        ],
        compilerOptions: {
            paths: {
                [`${name}/cypress`]: ["./src/cypress/index.ts"],
                [`${name}/selectors`]: ["./src/selectors/index.ts"],
                [name]: ["./src/index.ts"],
            },
        },
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigSelectors(
    options: Options,
): Promise<string | null> {
    if (!options.enableSelectors) {
        return null;
    }
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.selectors.json",
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigPageobjects(
    options: Options,
): Promise<string | null> {
    if (!options.enablePageobjects) {
        return null;
    }
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.pageobjects.json",
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

async function readJsonFile<T = unknown>(filePath: string): Promise<T> {
    const content = await fs.readFile(filePath, "utf8");
    return JSON.parse(content) as T;
}

async function writeJsonFile(
    cwd: string,
    filename: string,
    content: string,
): Promise<void> {
    const filePath = path.join(cwd, filename);
    await fs.writeFile(filePath, content, "utf8");
    console.log(filename, "written");
}

async function findCypressConfigPath(cwd: string): Promise<string> {
    const { findUp } = await import("find-up");
    const absolutePath = await findUp("cypress/tsconfig.json", { cwd });
    if (absolutePath) {
        return path.relative(cwd, absolutePath).replaceAll("\\", "/");
    }
    return "cypress/tsconfig.json";
}

function isTSConfigFile(filename: string): boolean {
    return filename.startsWith("tsconfig.") && filename.endsWith(".json");
}

/**
 * @public
 */
export async function run(cwd: string, argv: string[]): Promise<void> {
    const flags = new Set(argv.filter((it) => it.startsWith("--")));

    if (flags.has("--help")) {
        console.log("usage: fk-write-config [OPTIONS..]");
        console.log(`
  --help                     Show this help.
  --with-jest                Use Jest as test runner.
  --with-vitest              Use Vitest as test runner.
`);
        return;
    }

    const pkg = await readJsonFile<PackageJson>(path.join(cwd, "package.json"));
    const cypressConfigPath = await findCypressConfigPath(cwd);
    const testRunner = detectTestRunner(flags);
    const options: Options = {
        name: pkg.name,
        cypressConfigPath,
        testRunner,
        enablePageobjects: Boolean(pkg.exports?.["./cypress"]),
        enableSelectors: Boolean(pkg.exports?.["./selectors"]),
    };
    const generated = new Map([
        ["tsconfig.json", generateTsconfig(options)],
        ["tsconfig.lib.json", generateTsconfigLib(options)],
        ["tsconfig.cypress.json", generateTsconfigCypress(options)],
        ["tsconfig.selectors.json", generateTsconfigSelectors(options)],
        ["tsconfig.pageobjects.json", generateTsconfigPageobjects(options)],
    ]);

    console.group("Writing TypeScript configuration");
    console.log("Test runner:", testRunner);
    console.log();

    /* write new files */
    const written = new Set<string>();
    for (const [filename, promise] of generated.entries()) {
        const content = await promise;
        if (content) {
            await writeJsonFile(cwd, filename, content);
            written.add(filename);
        }
    }

    /* remove any other tsconfig files */
    const entries = await fs.readdir(cwd);
    for (const entry of entries) {
        if (isTSConfigFile(entry) && !written.has(entry)) {
            await fs.unlink(path.join(cwd, entry));
            console.log(entry, "removed");
        }
    }

    console.groupEnd();
}
