import fs from "node:fs/promises";
import path from "node:path";
import { styleText } from "node:util";
import detectIndent from "detect-indent";

const boilerplate = `/* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */`;

/**
 * @internal
 */
export interface PackageJson {
    name: string;
    scripts?: Partial<Record<string, string>>;
    exports?: Record<string, unknown>;
    devDependencies?: Record<string, string>;
}

interface TSConfig {
    extends?: string | string[];
    references?: Array<{ path: string }>;
    compilerOptions?: {
        declarationDir?: string;
        types?: string[];
        paths?: Record<string, string[] | undefined>;
    };
    include?: string[];
    exclude?: string[];
}

/**
 * @internal
 */
export interface Options {
    /** name from package.json */
    name: string;

    /** path to "etc" folder or null to use default */
    apiExtractorReportFolder: string | null;

    /** path to cypress tsconfig */
    cypressConfigPath: string;

    /** test runner used in this repository */
    testRunner: "jest" | "vitest";

    /* true if api-extractor is detected */
    enableApiExtractor: boolean;

    /* true if selector objects are present */
    enableSelectors: boolean;

    /* true if cypress pageobjects are present */
    enablePageobjects: boolean;
}

function detectTestRunner(flags: Set<string>): "jest" | "vitest" {
    if (flags.has("--with-jest")) {
        return "jest";
    }
    if (flags.has("--with-vitest")) {
        return "vitest";
    }
    return "vitest";
}

async function serializeJson(data: unknown): Promise<string> {
    const { format, resolveConfig } = await import("prettier");
    const content = JSON.stringify(data, null, 4);
    const filepath = "tsconfig.json";
    const config = await resolveConfig(filepath, { editorconfig: true });
    const formatted = await format(content, { ...config, filepath });
    return formatted;
}

/**
 * @internal
 */
export async function generateApiExtractorLib(
    options: Pick<Options, "apiExtractorReportFolder" | "enableApiExtractor">,
): Promise<string | null> {
    if (!options.enableApiExtractor) {
        return null;
    }
    const config = {
        $schema:
            "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
        extends:
            "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
        compiler: {
            tsconfigFilePath: "<projectFolder>/tsconfig.lib.json",
        },
        apiReport: {
            reportFileName: "<unscopedPackageName>.api.md",
            reportFolder: options.apiExtractorReportFolder
                ? `<projectFolder>/${options.apiExtractorReportFolder}`
                : undefined,
        },
        docModel: {
            enabled: true,
        },
        dtsRollup: {
            publicTrimmedFilePath: "<projectFolder>/dist/types/index.d.ts",
        },
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateApiExtractorCypress(
    options: Pick<
        Options,
        "apiExtractorReportFolder" | "enableApiExtractor" | "enablePageobjects"
    >,
): Promise<string | null> {
    if (!options.enableApiExtractor) {
        return null;
    }
    if (!options.enablePageobjects) {
        return null;
    }
    const config = {
        $schema:
            "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
        extends:
            "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
        mainEntryPointFilePath: "<projectFolder>/temp/types/cypress/index.d.ts",
        compiler: {
            tsconfigFilePath: "<projectFolder>/tsconfig.pageobjects.json",
        },
        apiReport: {
            reportFileName: "<unscopedPackageName>-cypress.api.md",
            reportFolder: options.apiExtractorReportFolder
                ? `<projectFolder>/${options.apiExtractorReportFolder}`
                : undefined,
        },
        dtsRollup: {
            publicTrimmedFilePath: "<projectFolder>/dist/types/cypress.d.ts",
        },
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateApiExtractorSelectors(
    options: Pick<
        Options,
        "apiExtractorReportFolder" | "enableApiExtractor" | "enableSelectors"
    >,
): Promise<string | null> {
    if (!options.enableApiExtractor) {
        return null;
    }
    if (!options.enableSelectors) {
        return null;
    }
    const config = {
        $schema:
            "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
        extends:
            "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
        mainEntryPointFilePath:
            "<projectFolder>/temp/types/selectors/index.d.ts",
        compiler: {
            tsconfigFilePath: "<projectFolder>/tsconfig.selectors.json",
        },
        apiReport: {
            reportFileName: "<unscopedPackageName>-selectors.api.md",
            reportFolder: options.apiExtractorReportFolder
                ? `<projectFolder>/${options.apiExtractorReportFolder}`
                : undefined,
        },
        dtsRollup: {
            publicTrimmedFilePath: "<projectFolder>/dist/types/selectors.d.ts",
        },
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfig(options: Options): Promise<string> {
    const { name, enablePageobjects, enableSelectors, testRunner } = options;
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.root.json",
        compilerOptions: undefined,
        include: undefined,
        exclude: undefined,
        references: [
            { path: "./tsconfig.lib.json" },
            { path: "./tsconfig.cypress.json" },
        ],
    };
    if (testRunner === "jest") {
        config.extends = [
            "@forsakringskassan/vite-lib-config/tsconfig.root.json",
            "@fkui/tsconfig/recommended",
            "@fkui/tsconfig/vue",
        ];
        config.compilerOptions = {
            declarationDir: "temp/jest",
            paths: {
                [name]: ["./src/index.ts"],
            },
        };
        config.include = ["src/@types/*.ts"];
        config.exclude = ["src/@types/cypress.d.ts"];
    }
    if (enablePageobjects) {
        config.references?.push({ path: "./tsconfig.pageobjects.json" });
    }
    if (enableSelectors) {
        config.references?.push({ path: "./tsconfig.selectors.json" });
    }
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigLib(
    options: Pick<
        Options,
        "name" | "testRunner" | "enablePageobjects" | "enableSelectors"
    >,
): Promise<string> {
    const { name, testRunner } = options;
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
        compilerOptions: {
            types:
                testRunner === "jest"
                    ? ["node", "jest", "vite/client"]
                    : undefined,
            paths: {
                [`${name}/cypress`]: options.enablePageobjects
                    ? ["./src/cypress/index.ts"]
                    : undefined,
                [`${name}/selectors`]: options.enableSelectors
                    ? ["./src/selectors/index.ts"]
                    : undefined,
                [name]: ["./src/index.ts"],
            },
        },
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigCypress(
    options: Pick<
        Options,
        "name" | "cypressConfigPath" | "enablePageobjects" | "enableSelectors"
    >,
): Promise<string> {
    const { name, cypressConfigPath } = options;
    const config: TSConfig = {
        extends: [
            cypressConfigPath,
            "@forsakringskassan/vite-lib-config/tsconfig.cypress.json",
        ],
        compilerOptions: {
            paths: {
                [`${name}/cypress`]: options.enablePageobjects
                    ? ["./src/cypress/index.ts"]
                    : undefined,
                [`${name}/selectors`]: options.enableSelectors
                    ? ["./src/selectors/index.ts"]
                    : undefined,
                [name]: ["./src/index.ts"],
            },
        },
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigSelectors(
    options: Options,
): Promise<string | null> {
    if (!options.enableSelectors) {
        return null;
    }
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.selectors.json",
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export async function generateTsconfigPageobjects(
    options: Options,
): Promise<string | null> {
    if (!options.enablePageobjects) {
        return null;
    }
    const config: TSConfig = {
        extends: "@forsakringskassan/vite-lib-config/tsconfig.pageobjects.json",
    };
    return [boilerplate, await serializeJson(config)].join("\n\n");
}

/**
 * @internal
 */
export function generateViteConfig(): string {
    const config = [
        `import { defineConfig } from "@forsakringskassan/vite-lib-config/vite";`,
        `import { defineTestConfig } from "@forsakringskassan/vitest-config-jsdom";`,
        ``,
        `export default defineConfig({`,
        `    test: defineTestConfig(),`,
        `});`,
    ]
        .map((it) => `${it}\n`)
        .join("");
    return [boilerplate, config].join("\n\n");
}

/* eslint-disable-next-line @typescript-eslint/no-unnecessary-type-parameters -- used to lie about the return value */
async function readJsonFile<T = unknown>(
    cwd: string,
    filename: string,
): Promise<{ data: T; indent: string; trailer: string }> {
    const filePath = path.join(cwd, filename);
    const content = await fs.readFile(filePath, "utf8");
    const data = JSON.parse(content) as T;
    const { indent } = detectIndent(content);
    const trailer = content.endsWith("\n") ? "\n" : "";
    return { data, indent, trailer };
}

async function writeJsonFile(
    cwd: string,
    filename: string,
    content: string,
): Promise<void> {
    const filePath = path.join(cwd, filename);
    await fs.writeFile(filePath, content, "utf8");
    console.log(filename, "written");
}

/**
 * @internal
 */
export function updateBuildScripts(
    pkg: PackageJson,
    options: Pick<
        Options,
        "enableApiExtractor" | "enableSelectors" | "enablePageobjects"
    >,
): PackageJson {
    const result = { ...pkg, scripts: { ...pkg.scripts } };
    const haveBuildMock = Boolean(result.scripts["build:mock"]);
    const buildSelectors = options.enableSelectors || options.enablePageobjects;
    result.scripts.build = [
        "run-s",
        "build:lib",
        haveBuildMock ? "build:mock" : null,
        buildSelectors ? "build:selectors" : null,
        "build:dts",
        options.enableApiExtractor ? "build:api" : null,
    ]
        .filter(Boolean)
        .join(" ");
    result.scripts["build:api"] = options.enableApiExtractor
        ? "fk-api-extractor api-extractor.*.json"
        : undefined;
    result.scripts["build:dts"] = "vue-tsc -b";
    result.scripts["build:lib"] = "fk-build-vue-lib --clean";
    result.scripts["build:selectors"] = buildSelectors
        ? "fk-build-selectors"
        : undefined;
    delete result.scripts["build:pageobject"];
    result.scripts.prebuild = undefined;
    return result;
}

async function writeBuildScripts(cwd: string, options: Options): Promise<void> {
    const result = await readJsonFile<PackageJson>(cwd, "package.json");
    const { data: pkg, indent, trailer } = result;
    const updated = JSON.stringify(
        updateBuildScripts(pkg, options),
        undefined,
        indent,
    );
    await writeJsonFile(cwd, "package.json", `${updated}${trailer}`);
}

async function findApiExtractorReportFolder(
    cwd: string,
): Promise<string | null> {
    const { findUp } = await import("find-up");
    const absolutePath = await findUp("package-lock.json", { cwd });

    /* use default path if not found */
    if (!absolutePath) {
        return null;
    }

    /* use default path if found in the current directory */
    const rootDir = path.dirname(absolutePath);
    if (path.resolve(cwd) === rootDir) {
        return null;
    }

    return path.relative(cwd, path.join(rootDir, "etc")).replaceAll("\\", "/");
}

async function findCypressConfigPath(cwd: string): Promise<string> {
    const { findUp } = await import("find-up");
    const absolutePath = await findUp("cypress/tsconfig.json", { cwd });
    if (absolutePath) {
        return path.relative(cwd, absolutePath).replaceAll("\\", "/");
    }
    return "./cypress/tsconfig.json";
}

function shouldPrune(filename: string): boolean {
    if (filename.startsWith("tsconfig.") && filename.endsWith(".json")) {
        return true;
    }
    if (filename.startsWith("api-extractor.") && filename.endsWith(".json")) {
        return true;
    }
    return false;
}

function flagEnabled(value: boolean): string {
    return value ? styleText("green", "enabled") : styleText("red", "disabled");
}

/**
 * @public
 */
export async function run(cwd: string, argv: string[]): Promise<void> {
    const flags = new Set(argv.filter((it) => it.startsWith("--")));

    if (flags.has("--help")) {
        console.log("usage: fk-write-config [OPTIONS..]");
        console.log(`
  --help                     Show this help.
  --with-api-extractor       Use @microsoft/api-extractor.
  --with-jest                Use Jest as test runner.
  --with-vitest              Use Vitest as test runner.
`);
        return;
    }

    const { data: pkg } = await readJsonFile<PackageJson>(cwd, "package.json");

    /* sanity check: if the package does not use
     * `@forsakringskassan/vite-lib-config` the configuration should not be
     * written either */
    if (!pkg.devDependencies?.["@forsakringskassan/vite-lib-config"]) {
        console.error(
            `The "${pkg.name}" does not use "@forsakringskassan/vite-lib-config".`,
        );
        console.error(`Skipping writing configuration.`);
        return;
    }

    const apiExtractorReportFolder = await findApiExtractorReportFolder(cwd);
    const cypressConfigPath = await findCypressConfigPath(cwd);
    const testRunner = detectTestRunner(flags);
    const options: Options = {
        name: pkg.name,
        apiExtractorReportFolder,
        cypressConfigPath,
        testRunner,
        enableApiExtractor: flags.has("--with-api-extractor"),
        enablePageobjects: Boolean(pkg.exports?.["./cypress"]),
        enableSelectors: Boolean(pkg.exports?.["./selectors"]),
    };
    const generated = new Map<string, string | null | Promise<string | null>>([
        ["api-extractor.json", null],
        ["api-extractor.lib.json", generateApiExtractorLib(options)],
        ["api-extractor.cypress.json", generateApiExtractorCypress(options)],
        [
            "api-extractor.selectors.json",
            generateApiExtractorSelectors(options),
        ],
        ["tsconfig.json", generateTsconfig(options)],
        ["tsconfig.lib.json", generateTsconfigLib(options)],
        ["tsconfig.cypress.json", generateTsconfigCypress(options)],
        ["tsconfig.selectors.json", generateTsconfigSelectors(options)],
        ["tsconfig.pageobjects.json", generateTsconfigPageobjects(options)],
        ["vite.config.ts", null],
        ["vite.config.mts", generateViteConfig()],
        ["vitest.setup.ts", null],
    ]);

    console.group("Writing configuration files");
    console.log("API Extractor:", flagEnabled(options.enableApiExtractor));
    console.log("Cypress pageobjects:", flagEnabled(options.enablePageobjects));
    console.log("Selector objects:", flagEnabled(options.enableSelectors));
    console.log("Test runner:", styleText("cyan", testRunner));
    console.log();

    /* write new files */
    const written = new Set<string>();
    const omitted = new Set<string>();
    for (const [filename, promise] of generated) {
        const content = await promise;
        if (content) {
            await writeJsonFile(cwd, filename, content);
            written.add(filename);
        } else {
            omitted.add(filename);
        }
    }

    /* remove any other tsconfig files */
    const entries = await fs.readdir(cwd);
    for (const entry of entries) {
        if (written.has(entry)) {
            continue;
        }

        if (omitted.has(entry) || shouldPrune(entry)) {
            await fs.unlink(path.join(cwd, entry));
            console.log(entry, "removed");
        }
    }

    await writeBuildScripts(cwd, options);

    console.groupEnd();
    console.log();
}
