import { describe, expect, it } from "vitest";
import { type PackageJson } from "./package-json";
import {
    type Options,
    generateApiExtractorCypress,
    generateApiExtractorLib,
    generateApiExtractorSelectors,
    generateTsconfig,
    generateTsconfigCypress,
    generateTsconfigLib,
    generateTsconfigPageobjects,
    generateTsconfigSelectors,
    generateViteConfig,
    updateBuildScripts,
} from "./write-config";

expect.addSnapshotSerializer({
    test(value) {
        return typeof value === "string";
    },
    serialize: String,
});

it("should not reference tsconfig.pageobjects.json when pageobjects are not detected", async () => {
    expect.assertions(1);
    const options: Options = {
        name: "@fkui/vue",
        apiExtractorReportFolder: null,
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "vitest",
        enableApiExtractor: false,
        enablePageobjects: false,
        enableSelectors: true,
    };
    const result = await generateTsconfig(options);
    expect(result).toMatchInlineSnapshot(`
        /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

        {
            "extends": "@forsakringskassan/vite-lib-config/tsconfig.root.json",
            "references": [
                {
                    "path": "./tsconfig.lib.json"
                },
                {
                    "path": "./tsconfig.cypress.json"
                },
                {
                    "path": "./tsconfig.selectors.json"
                }
            ]
        }

    `);
});

it("should not reference tsconfig.selectors.json when selectors are not detected", async () => {
    expect.assertions(1);
    const options: Options = {
        name: "@fkui/vue",
        apiExtractorReportFolder: null,
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "vitest",
        enableApiExtractor: false,
        enablePageobjects: true,
        enableSelectors: false,
    };
    const result = await generateTsconfig(options);
    expect(result).toMatchInlineSnapshot(`
        /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

        {
            "extends": "@forsakringskassan/vite-lib-config/tsconfig.root.json",
            "references": [
                {
                    "path": "./tsconfig.lib.json"
                },
                {
                    "path": "./tsconfig.cypress.json"
                },
                {
                    "path": "./tsconfig.pageobjects.json"
                }
            ]
        }

    `);
});

describe("tsconfig.lib.json", () => {
    it("should omit cypress alias when cypress pageobjects are disabled", async () => {
        expect.assertions(1);
        const result = await generateTsconfigLib({
            name: "@fkui/vue",
            testRunner: "vitest",
            enablePageobjects: false,
            enableSelectors: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "extends": "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
              "compilerOptions": {
                  "paths": {
                      "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                      "@fkui/vue": ["./src/index.ts"]
                  }
              }
          }
        `);
    });

    it("should omit selectors alias when selector objects are disabled", async () => {
        expect.assertions(1);
        const result = await generateTsconfigLib({
            name: "@fkui/vue",
            testRunner: "vitest",
            enablePageobjects: true,
            enableSelectors: false,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "extends": "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
              "compilerOptions": {
                  "paths": {
                      "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                      "@fkui/vue": ["./src/index.ts"]
                  }
              }
          }
        `);
    });
});

describe("tsconfig.cypress.json", () => {
    it("should omit cypress alias when cypress pageobjects are disabled", async () => {
        expect.assertions(1);
        const result = await generateTsconfigCypress({
            name: "@fkui/vue",
            cypressConfigPath: "../../cypress/tsconfig.json",
            enablePageobjects: false,
            enableSelectors: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "extends": [
                  "../../cypress/tsconfig.json",
                  "@forsakringskassan/vite-lib-config/tsconfig.cypress.json"
              ],
              "compilerOptions": {
                  "paths": {
                      "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                      "@fkui/vue": ["./src/index.ts"]
                  }
              }
          }
        `);
    });

    it("should omit selectors alias when selector objects are disabled", async () => {
        expect.assertions(1);
        const result = await generateTsconfigCypress({
            name: "@fkui/vue",
            cypressConfigPath: "../../cypress/tsconfig.json",
            enablePageobjects: true,
            enableSelectors: false,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "extends": [
                  "../../cypress/tsconfig.json",
                  "@forsakringskassan/vite-lib-config/tsconfig.cypress.json"
              ],
              "compilerOptions": {
                  "paths": {
                      "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                      "@fkui/vue": ["./src/index.ts"]
                  }
              }
          }
        `);
    });
});

describe("with vitest as test runner", () => {
    const options: Options = {
        name: "@fkui/vue",
        apiExtractorReportFolder: null,
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "vitest",
        enableApiExtractor: false,
        enablePageobjects: true,
        enableSelectors: true,
    };

    it("should generate tsconfig.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfig(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.root.json",
                "references": [
                    {
                        "path": "./tsconfig.lib.json"
                    },
                    {
                        "path": "./tsconfig.cypress.json"
                    },
                    {
                        "path": "./tsconfig.pageobjects.json"
                    },
                    {
                        "path": "./tsconfig.selectors.json"
                    }
                ]
            }

        `);
    });

    it("should generate tsconfig.lib.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigLib(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
                "compilerOptions": {
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.cypress.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigCypress(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": [
                    "../../cypress/tsconfig.json",
                    "@forsakringskassan/vite-lib-config/tsconfig.cypress.json"
                ],
                "compilerOptions": {
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.selectors.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigSelectors(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.selectors.json"
            }

        `);
    });

    it("should generate tsconfig.pageobjects.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigPageobjects(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.pageobjects.json"
            }

        `);
    });
});

describe("with jest as test runner", () => {
    const options: Options = {
        name: "@fkui/vue",
        apiExtractorReportFolder: null,
        cypressConfigPath: "../../cypress/tsconfig.json",
        testRunner: "jest",
        enableApiExtractor: false,
        enablePageobjects: true,
        enableSelectors: true,
    };

    it("should generate tsconfig.json extending", async () => {
        expect.assertions(1);
        const result = await generateTsconfig(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": [
                    "@forsakringskassan/vite-lib-config/tsconfig.root.json",
                    "@fkui/tsconfig/recommended",
                    "@fkui/tsconfig/vue"
                ],
                "compilerOptions": {
                    "declarationDir": "temp/jest",
                    "paths": {
                        "@fkui/vue": ["./src/index.ts"]
                    }
                },
                "include": ["src/@types/*.ts"],
                "exclude": ["src/@types/cypress.d.ts"],
                "references": [
                    {
                        "path": "./tsconfig.lib.json"
                    },
                    {
                        "path": "./tsconfig.cypress.json"
                    },
                    {
                        "path": "./tsconfig.pageobjects.json"
                    },
                    {
                        "path": "./tsconfig.selectors.json"
                    }
                ]
            }

        `);
    });

    it("should generate tsconfig.lib.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigLib(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.lib.json",
                "compilerOptions": {
                    "types": ["node", "jest", "vite/client"],
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.cypress.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigCypress(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": [
                    "../../cypress/tsconfig.json",
                    "@forsakringskassan/vite-lib-config/tsconfig.cypress.json"
                ],
                "compilerOptions": {
                    "paths": {
                        "@fkui/vue/cypress": ["./src/cypress/index.ts"],
                        "@fkui/vue/selectors": ["./src/selectors/index.ts"],
                        "@fkui/vue": ["./src/index.ts"]
                    }
                }
            }

        `);
    });

    it("should generate tsconfig.selectors.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigSelectors(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.selectors.json"
            }

        `);
    });

    it("should generate tsconfig.pageobjects.json", async () => {
        expect.assertions(1);
        const result = await generateTsconfigPageobjects(options);
        expect(result).toMatchInlineSnapshot(`
            /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

            {
                "extends": "@forsakringskassan/vite-lib-config/tsconfig.pageobjects.json"
            }

        `);
    });
});

describe("api-extractor", () => {
    it("should generate lib config when api-extractor is enabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorLib({
            apiExtractorReportFolder: null,
            enableApiExtractor: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
              "extends": "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
              "compiler": {
                  "tsconfigFilePath": "<projectFolder>/tsconfig.lib.json"
              },
              "apiReport": {
                  "reportFileName": "<unscopedPackageName>.api.md"
              },
              "docModel": {
                  "enabled": true
              },
              "dtsRollup": {
                  "publicTrimmedFilePath": "<projectFolder>/dist/types/index.d.ts"
              }
          }
        `);
    });

    it("should generate lib config with a different report folder", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorLib({
            apiExtractorReportFolder: "../../etc",
            enableApiExtractor: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
              "extends": "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
              "compiler": {
                  "tsconfigFilePath": "<projectFolder>/tsconfig.lib.json"
              },
              "apiReport": {
                  "reportFileName": "<unscopedPackageName>.api.md",
                  "reportFolder": "<projectFolder>/../../etc"
              },
              "docModel": {
                  "enabled": true
              },
              "dtsRollup": {
                  "publicTrimmedFilePath": "<projectFolder>/dist/types/index.d.ts"
              }
          }
        `);
    });

    it("should generate cypress config when api-extractor is enabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorCypress({
            apiExtractorReportFolder: null,
            enableApiExtractor: true,
            enablePageobjects: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
              "extends": "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
              "mainEntryPointFilePath": "<projectFolder>/temp/types/cypress/index.d.ts",
              "compiler": {
                  "tsconfigFilePath": "<projectFolder>/tsconfig.pageobjects.json"
              },
              "apiReport": {
                  "reportFileName": "<unscopedPackageName>-cypress.api.md"
              },
              "dtsRollup": {
                  "publicTrimmedFilePath": "<projectFolder>/dist/types/cypress.d.ts"
              }
          }
        `);
    });

    it("should generate cypress config with different report folder", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorCypress({
            apiExtractorReportFolder: "../../etc",
            enableApiExtractor: true,
            enablePageobjects: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
              "extends": "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
              "mainEntryPointFilePath": "<projectFolder>/temp/types/cypress/index.d.ts",
              "compiler": {
                  "tsconfigFilePath": "<projectFolder>/tsconfig.pageobjects.json"
              },
              "apiReport": {
                  "reportFileName": "<unscopedPackageName>-cypress.api.md",
                  "reportFolder": "<projectFolder>/../../etc"
              },
              "dtsRollup": {
                  "publicTrimmedFilePath": "<projectFolder>/dist/types/cypress.d.ts"
              }
          }
        `);
    });

    it("should generate selector config when api-extractor is enabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorSelectors({
            apiExtractorReportFolder: null,
            enableApiExtractor: true,
            enableSelectors: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
              "extends": "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
              "mainEntryPointFilePath": "<projectFolder>/temp/types/selectors/index.d.ts",
              "compiler": {
                  "tsconfigFilePath": "<projectFolder>/tsconfig.selectors.json"
              },
              "apiReport": {
                  "reportFileName": "<unscopedPackageName>-selectors.api.md"
              },
              "dtsRollup": {
                  "publicTrimmedFilePath": "<projectFolder>/dist/types/selectors.d.ts"
              }
          }
        `);
    });

    it("should generate selector config with different report folder", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorSelectors({
            apiExtractorReportFolder: "../../etc",
            enableApiExtractor: true,
            enableSelectors: true,
        });
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          {
              "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
              "extends": "@forsakringskassan/vite-lib-config/api-extractor/api-extractor.json",
              "mainEntryPointFilePath": "<projectFolder>/temp/types/selectors/index.d.ts",
              "compiler": {
                  "tsconfigFilePath": "<projectFolder>/tsconfig.selectors.json"
              },
              "apiReport": {
                  "reportFileName": "<unscopedPackageName>-selectors.api.md",
                  "reportFolder": "<projectFolder>/../../etc"
              },
              "dtsRollup": {
                  "publicTrimmedFilePath": "<projectFolder>/dist/types/selectors.d.ts"
              }
          }
        `);
    });

    it("should not generate lib config when api-extractor is disabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorLib({
            apiExtractorReportFolder: null,
            enableApiExtractor: false,
        });
        expect(result).toMatchInlineSnapshot(`null`);
    });

    it("should not generate cypress config when api-extractor is disabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorCypress({
            apiExtractorReportFolder: null,
            enableApiExtractor: false,
            enablePageobjects: true,
        });
        expect(result).toMatchInlineSnapshot(`null`);
    });

    it("should not generate cypress config when cypress is disabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorCypress({
            apiExtractorReportFolder: null,
            enableApiExtractor: true,
            enablePageobjects: false,
        });
        expect(result).toMatchInlineSnapshot(`null`);
    });

    it("should not generate selector config when api-extractor is disabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorSelectors({
            apiExtractorReportFolder: null,
            enableApiExtractor: false,
            enableSelectors: true,
        });
        expect(result).toMatchInlineSnapshot(`null`);
    });

    it("should not generate selector config when selectors are disabled", async () => {
        expect.assertions(1);
        const result = await generateApiExtractorSelectors({
            apiExtractorReportFolder: null,
            enableApiExtractor: true,
            enableSelectors: false,
        });
        expect(result).toMatchInlineSnapshot(`null`);
    });
});

describe("build scripts", () => {
    it("should write build scripts", () => {
        expect.assertions(1);
        const pkg: PackageJson = {
            name: "mock-pkg",
            version: "1.2.3",
        };
        const updated = updateBuildScripts(pkg, {
            enableApiExtractor: false,
            enableSelectors: false,
            enablePageobjects: false,
        });
        expect(JSON.stringify(updated, null, 2)).toMatchInlineSnapshot(`
          {
            "name": "mock-pkg",
            "version": "1.2.3",
            "scripts": {
              "build": "run-s build:lib build:dts",
              "build:dts": "vue-tsc -b",
              "build:lib": "fk-build-vue-lib --clean"
            }
          }
        `);
    });

    it("should write build scripts (with api-extractor)", () => {
        expect.assertions(1);
        const pkg: PackageJson = {
            name: "mock-pkg",
            version: "1.2.3",
        };
        const updated = updateBuildScripts(pkg, {
            enableApiExtractor: true,
            enableSelectors: false,
            enablePageobjects: false,
        });
        expect(JSON.stringify(updated, null, 2)).toMatchInlineSnapshot(`
          {
            "name": "mock-pkg",
            "version": "1.2.3",
            "scripts": {
              "build": "run-s build:lib build:dts build:api",
              "build:api": "fk-api-extractor api-extractor.*.json",
              "build:dts": "vue-tsc -b",
              "build:lib": "fk-build-vue-lib --clean"
            }
          }
        `);
    });

    it("should write build scripts (with selectors)", () => {
        expect.assertions(1);
        const pkg: PackageJson = {
            name: "mock-pkg",
            version: "1.2.3",
        };
        const updated = updateBuildScripts(pkg, {
            enableApiExtractor: false,
            enableSelectors: true,
            enablePageobjects: false,
        });
        expect(JSON.stringify(updated, null, 2)).toMatchInlineSnapshot(`
          {
            "name": "mock-pkg",
            "version": "1.2.3",
            "scripts": {
              "build": "run-s build:lib build:dts",
              "build:dts": "vue-tsc -b",
              "build:lib": "fk-build-vue-lib --clean --selectors"
            }
          }
        `);
    });

    it("should write build scripts (with cypress pageobjects)", () => {
        expect.assertions(1);
        const pkg: PackageJson = {
            name: "mock-pkg",
            version: "1.2.3",
        };
        const updated = updateBuildScripts(pkg, {
            enableApiExtractor: false,
            enableSelectors: false,
            enablePageobjects: true,
        });
        expect(JSON.stringify(updated, null, 2)).toMatchInlineSnapshot(`
          {
            "name": "mock-pkg",
            "version": "1.2.3",
            "scripts": {
              "build": "run-s build:lib build:dts",
              "build:dts": "vue-tsc -b",
              "build:lib": "fk-build-vue-lib --clean --pageobjects"
            }
          }
        `);
    });

    it("should remove obsolete pageobject build script", () => {
        expect.assertions(1);
        const pkg: PackageJson = {
            name: "mock-pkg",
            version: "1.2.3",
            scripts: {
                "build:pageobject": "something",
            },
        };
        const updated = updateBuildScripts(pkg, {
            enableApiExtractor: false,
            enableSelectors: false,
            enablePageobjects: false,
        });
        expect(JSON.stringify(updated, null, 2)).toMatchInlineSnapshot(`
          {
            "name": "mock-pkg",
            "version": "1.2.3",
            "scripts": {
              "build": "run-s build:lib build:dts",
              "build:dts": "vue-tsc -b",
              "build:lib": "fk-build-vue-lib --clean"
            }
          }
        `);
    });

    it("should retain other existing build scripts", () => {
        expect.assertions(1);
        const pkg: PackageJson = {
            name: "mock-pkg",
            version: "1.2.3",
            scripts: {
                foo: "bar",
                "build:foo": "bar",
            },
        };
        const updated = updateBuildScripts(pkg, {
            enableApiExtractor: false,
            enableSelectors: false,
            enablePageobjects: false,
        });
        expect(JSON.stringify(updated, null, 2)).toMatchInlineSnapshot(`
          {
            "name": "mock-pkg",
            "version": "1.2.3",
            "scripts": {
              "foo": "bar",
              "build:foo": "bar",
              "build": "run-s build:lib build:dts",
              "build:dts": "vue-tsc -b",
              "build:lib": "fk-build-vue-lib --clean"
            }
          }
        `);
    });

    it("should call build:mock if present", () => {
        expect.assertions(1);
        const pkg: PackageJson = {
            name: "mock-pkg",
            version: "1.2.3",
            scripts: {
                "build:mock": "foo",
            },
        };
        const updated = updateBuildScripts(pkg, {
            enableApiExtractor: false,
            enableSelectors: false,
            enablePageobjects: false,
        });
        expect(JSON.stringify(updated, null, 2)).toMatchInlineSnapshot(`
          {
            "name": "mock-pkg",
            "version": "1.2.3",
            "scripts": {
              "build:mock": "foo",
              "build": "run-s build:lib build:mock build:dts",
              "build:dts": "vue-tsc -b",
              "build:lib": "fk-build-vue-lib --clean"
            }
          }
        `);
    });
});

describe("vite.config.mts", () => {
    it("should generate lib config when api-extractor is enabled", () => {
        expect.assertions(1);
        const result = generateViteConfig();
        expect(result).toMatchInlineSnapshot(`
          /* This file was generated by @forsakringskassan/vite-lib-config. Changes may be overwritten! */

          import { defineConfig } from "@forsakringskassan/vite-lib-config/vite";
          import { defineTestConfig } from "@forsakringskassan/vitest-config-jsdom";

          export default defineConfig({
              test: defineTestConfig(),
          });
        `);
    });
});
