name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x, 18.x, 20.x, 21.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: |
                  npm ci
            - name: ESLint
              run: npm run eslint
            - name: Prettier
              run: npm run prettier:check
            - name: Jest
              run: npm test --ignore-scripts
            - name: Build
              run: |
                  npm run --if-present build
                  npm pack
                  npm exec npm-pkg-lint
